"""
rfm_scoring.py
--------------
Calculates Recency, Frequency, and Monetary (RFM) values for each customer,
then scales them for use in KMeans clustering.

RFM Definitions
---------------
Recency   : Days since the customer's last purchase (lower = better)
Frequency : Total number of unique invoices (higher = better)
Monetary  : Total revenue generated by the customer (higher = better)

Scaling
-------
KMeans is distance-based so features must be on the same scale.
We use StandardScaler after log-transforming Monetary and Frequency
to reduce the effect of outliers (revenue distributions are heavily
right-skewed in e-commerce data).
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler


def calculate_rfm(df: pd.DataFrame) -> pd.DataFrame:
    """
    Compute RFM metrics at the customer level.

    Parameters
    ----------
    df : pd.DataFrame
        Cleaned transaction-level DataFrame from data_prep.

    Returns
    -------
    pd.DataFrame
        Customer-level DataFrame with columns:
        CustomerID, Recency, Frequency, Monetary
    """
    # Snapshot date: one day after the last transaction in the dataset
    snapshot_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)
    print(f"  Snapshot date for recency: {snapshot_date.date()}")

    rfm = (
        df.groupby("CustomerID")
        .agg(
            Recency   = ("InvoiceDate",  lambda x: (snapshot_date - x.max()).days),
            Frequency = ("InvoiceNo",    "nunique"),
            Monetary  = ("LineRevenue",  "sum"),
        )
        .reset_index()
    )

    print(f"  Customers in RFM table: {len(rfm):,}")
    print(f"\n  RFM Summary Statistics:")
    print(rfm[["Recency", "Frequency", "Monetary"]].describe().round(2).to_string())
    return rfm


def scale_rfm(rfm: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, StandardScaler]:
    """
    Log-transform and standardize RFM features for clustering.

    Log transform reduces right skew in Frequency and Monetary.
    Recency is inverted (higher recency days = less recent) but left
    as-is since StandardScaler handles the directionality for KMeans.

    Parameters
    ----------
    rfm : pd.DataFrame
        Output of calculate_rfm().

    Returns
    -------
    rfm_log    : pd.DataFrame  Log-transformed (pre-scaling) values
    rfm_scaled : pd.DataFrame  Scaled values ready for KMeans
    scaler     : StandardScaler  Fitted scaler (for inverse transforms)
    """
    rfm_log = rfm.copy()
    rfm_log["Frequency"] = np.log1p(rfm["Frequency"])
    rfm_log["Monetary"]  = np.log1p(rfm["Monetary"])
    # Recency: log-transform days (also right-skewed)
    rfm_log["Recency"]   = np.log1p(rfm["Recency"])

    scaler = StandardScaler()
    scaled_values = scaler.fit_transform(rfm_log[["Recency", "Frequency", "Monetary"]])

    rfm_scaled = pd.DataFrame(
        scaled_values,
        columns=["Recency_scaled", "Frequency_scaled", "Monetary_scaled"],
        index=rfm.index
    )
    rfm_scaled.insert(0, "CustomerID", rfm["CustomerID"])

    print("\n  RFM features log-transformed and scaled ✅")
    return rfm_log, rfm_scaled, scaler


def run_rfm_pipeline(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, StandardScaler]:
    """
    Full RFM pipeline: calculate → log-transform → scale.

    Returns
    -------
    rfm        : raw RFM values
    rfm_log    : log-transformed values
    rfm_scaled : scaled values for clustering
    scaler     : fitted StandardScaler
    """
    print("\nCalculating RFM metrics...")
    rfm        = calculate_rfm(df)
    rfm_log, rfm_scaled, scaler = scale_rfm(rfm)
    return rfm, rfm_log, rfm_scaled, scaler
